---
- name: Pull and Run docker image
  hosts: all
  tasks:
    - name: Pull dheerajkarnam/calculator-spe-devops
      docker_image:
        name: dheerajkarnam/calculator-spe-devops
        source: pull

#    - name: Copy jar file to home directory
#      copy:
#        src: ./target/Lab3Junit-1.0-SNAPSHOT.jar
#        dest: ~/
#        mode: '0755'
